/**
 *
 * @author :    Mei XinLin
 * @version :   1.0
 */
'use strict';

export default {
  SIGN_UP: 'SIGN_UP',
  SIGN_UP_FULFILLED: 'SIGN_UP_FULFILLED',
  SIGN_UP_REJECTED: 'SIGN_UP_REJECTED',

  CHECK_USER_NAME: 'CHECK_USER_NAME',
  CHECK_USER_NAME_FULFILLED: 'CHECK_USER_NAME_FULFILLED',

  CHECK_EMAIL: 'CHECK_EMAIL',
  CHECK_EMAIL_FULFILLED: 'CHECK_EMAIL_FULFILLED',

  PASSWORD_CHANGE: 'PASSWORD_CHANGE',
  SECOND_PASSWORD_CHANGE: 'SECOND_PASSWORD_CHANGE'

}
