package com.may.dbTest.dao;

import com.may.dbTest.model.TSession;
import com.may.dbTest.model.TSessionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TSessionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_session
     *
     * @mbggenerated
     */
    int countByExample(TSessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_session
     *
     * @mbggenerated
     */
    int deleteByExample(TSessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_session
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long sessionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_session
     *
     * @mbggenerated
     */
    int insert(TSession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_session
     *
     * @mbggenerated
     */
    int insertSelective(TSession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_session
     *
     * @mbggenerated
     */
    List<TSession> selectByExample(TSessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_session
     *
     * @mbggenerated
     */
    TSession selectByPrimaryKey(Long sessionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_session
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TSession record, @Param("example") TSessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_session
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TSession record, @Param("example") TSessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_session
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TSession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_session
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TSession record);
}