package com.may.dbTest.dao;

import com.may.dbTest.model.TSet;
import com.may.dbTest.model.TSetExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TSetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_set
     *
     * @mbggenerated
     */
    int countByExample(TSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_set
     *
     * @mbggenerated
     */
    int deleteByExample(TSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_set
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long setId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_set
     *
     * @mbggenerated
     */
    int insert(TSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_set
     *
     * @mbggenerated
     */
    int insertSelective(TSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_set
     *
     * @mbggenerated
     */
    List<TSet> selectByExample(TSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_set
     *
     * @mbggenerated
     */
    TSet selectByPrimaryKey(Long setId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_set
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TSet record, @Param("example") TSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_set
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TSet record, @Param("example") TSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_set
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_set
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TSet record);
}