package com.may.dbTest.model;

import java.util.Date;

public class TSession {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_session.session_id
     *
     * @mbggenerated
     */
    private Long sessionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_session.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_session.session_date
     *
     * @mbggenerated
     */
    private Date sessionDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_session.session_commert
     *
     * @mbggenerated
     */
    private String sessionCommert;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_session
     *
     * @mbggenerated
     */
    public TSession(Long sessionId, String userId, Date sessionDate, String sessionCommert) {
        this.sessionId = sessionId;
        this.userId = userId;
        this.sessionDate = sessionDate;
        this.sessionCommert = sessionCommert;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_session
     *
     * @mbggenerated
     */
    public TSession() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_session.session_id
     *
     * @return the value of t_session.session_id
     *
     * @mbggenerated
     */
    public Long getSessionId() {
        return sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_session.session_id
     *
     * @param sessionId the value for t_session.session_id
     *
     * @mbggenerated
     */
    public void setSessionId(Long sessionId) {
        this.sessionId = sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_session.user_id
     *
     * @return the value of t_session.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_session.user_id
     *
     * @param userId the value for t_session.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_session.session_date
     *
     * @return the value of t_session.session_date
     *
     * @mbggenerated
     */
    public Date getSessionDate() {
        return sessionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_session.session_date
     *
     * @param sessionDate the value for t_session.session_date
     *
     * @mbggenerated
     */
    public void setSessionDate(Date sessionDate) {
        this.sessionDate = sessionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_session.session_commert
     *
     * @return the value of t_session.session_commert
     *
     * @mbggenerated
     */
    public String getSessionCommert() {
        return sessionCommert;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_session.session_commert
     *
     * @param sessionCommert the value for t_session.session_commert
     *
     * @mbggenerated
     */
    public void setSessionCommert(String sessionCommert) {
        this.sessionCommert = sessionCommert == null ? null : sessionCommert.trim();
    }
}