package com.may.dbTest.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class TSetExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_set
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_set
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_set
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_set
     *
     * @mbggenerated
     */
    public TSetExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_set
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_set
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_set
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_set
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_set
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_set
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_set
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_set
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_set
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_set
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_set
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCTime(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Time(value.getTime()), property);
        }

        protected void addCriterionForJDBCTime(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Time> timeList = new ArrayList<java.sql.Time>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                timeList.add(new java.sql.Time(iter.next().getTime()));
            }
            addCriterion(condition, timeList, property);
        }

        protected void addCriterionForJDBCTime(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Time(value1.getTime()), new java.sql.Time(value2.getTime()), property);
        }

        public Criteria andSetIdIsNull() {
            addCriterion("set_id is null");
            return (Criteria) this;
        }

        public Criteria andSetIdIsNotNull() {
            addCriterion("set_id is not null");
            return (Criteria) this;
        }

        public Criteria andSetIdEqualTo(Long value) {
            addCriterion("set_id =", value, "setId");
            return (Criteria) this;
        }

        public Criteria andSetIdNotEqualTo(Long value) {
            addCriterion("set_id <>", value, "setId");
            return (Criteria) this;
        }

        public Criteria andSetIdGreaterThan(Long value) {
            addCriterion("set_id >", value, "setId");
            return (Criteria) this;
        }

        public Criteria andSetIdGreaterThanOrEqualTo(Long value) {
            addCriterion("set_id >=", value, "setId");
            return (Criteria) this;
        }

        public Criteria andSetIdLessThan(Long value) {
            addCriterion("set_id <", value, "setId");
            return (Criteria) this;
        }

        public Criteria andSetIdLessThanOrEqualTo(Long value) {
            addCriterion("set_id <=", value, "setId");
            return (Criteria) this;
        }

        public Criteria andSetIdIn(List<Long> values) {
            addCriterion("set_id in", values, "setId");
            return (Criteria) this;
        }

        public Criteria andSetIdNotIn(List<Long> values) {
            addCriterion("set_id not in", values, "setId");
            return (Criteria) this;
        }

        public Criteria andSetIdBetween(Long value1, Long value2) {
            addCriterion("set_id between", value1, value2, "setId");
            return (Criteria) this;
        }

        public Criteria andSetIdNotBetween(Long value1, Long value2) {
            addCriterion("set_id not between", value1, value2, "setId");
            return (Criteria) this;
        }

        public Criteria andSessionIdIsNull() {
            addCriterion("session_id is null");
            return (Criteria) this;
        }

        public Criteria andSessionIdIsNotNull() {
            addCriterion("session_id is not null");
            return (Criteria) this;
        }

        public Criteria andSessionIdEqualTo(Long value) {
            addCriterion("session_id =", value, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdNotEqualTo(Long value) {
            addCriterion("session_id <>", value, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdGreaterThan(Long value) {
            addCriterion("session_id >", value, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdGreaterThanOrEqualTo(Long value) {
            addCriterion("session_id >=", value, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdLessThan(Long value) {
            addCriterion("session_id <", value, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdLessThanOrEqualTo(Long value) {
            addCriterion("session_id <=", value, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdIn(List<Long> values) {
            addCriterion("session_id in", values, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdNotIn(List<Long> values) {
            addCriterion("session_id not in", values, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdBetween(Long value1, Long value2) {
            addCriterion("session_id between", value1, value2, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdNotBetween(Long value1, Long value2) {
            addCriterion("session_id not between", value1, value2, "sessionId");
            return (Criteria) this;
        }

        public Criteria andPatternIdIsNull() {
            addCriterion("pattern_id is null");
            return (Criteria) this;
        }

        public Criteria andPatternIdIsNotNull() {
            addCriterion("pattern_id is not null");
            return (Criteria) this;
        }

        public Criteria andPatternIdEqualTo(Short value) {
            addCriterion("pattern_id =", value, "patternId");
            return (Criteria) this;
        }

        public Criteria andPatternIdNotEqualTo(Short value) {
            addCriterion("pattern_id <>", value, "patternId");
            return (Criteria) this;
        }

        public Criteria andPatternIdGreaterThan(Short value) {
            addCriterion("pattern_id >", value, "patternId");
            return (Criteria) this;
        }

        public Criteria andPatternIdGreaterThanOrEqualTo(Short value) {
            addCriterion("pattern_id >=", value, "patternId");
            return (Criteria) this;
        }

        public Criteria andPatternIdLessThan(Short value) {
            addCriterion("pattern_id <", value, "patternId");
            return (Criteria) this;
        }

        public Criteria andPatternIdLessThanOrEqualTo(Short value) {
            addCriterion("pattern_id <=", value, "patternId");
            return (Criteria) this;
        }

        public Criteria andPatternIdIn(List<Short> values) {
            addCriterion("pattern_id in", values, "patternId");
            return (Criteria) this;
        }

        public Criteria andPatternIdNotIn(List<Short> values) {
            addCriterion("pattern_id not in", values, "patternId");
            return (Criteria) this;
        }

        public Criteria andPatternIdBetween(Short value1, Short value2) {
            addCriterion("pattern_id between", value1, value2, "patternId");
            return (Criteria) this;
        }

        public Criteria andPatternIdNotBetween(Short value1, Short value2) {
            addCriterion("pattern_id not between", value1, value2, "patternId");
            return (Criteria) this;
        }

        public Criteria andSetLapIsNull() {
            addCriterion("set_lap is null");
            return (Criteria) this;
        }

        public Criteria andSetLapIsNotNull() {
            addCriterion("set_lap is not null");
            return (Criteria) this;
        }

        public Criteria andSetLapEqualTo(Short value) {
            addCriterion("set_lap =", value, "setLap");
            return (Criteria) this;
        }

        public Criteria andSetLapNotEqualTo(Short value) {
            addCriterion("set_lap <>", value, "setLap");
            return (Criteria) this;
        }

        public Criteria andSetLapGreaterThan(Short value) {
            addCriterion("set_lap >", value, "setLap");
            return (Criteria) this;
        }

        public Criteria andSetLapGreaterThanOrEqualTo(Short value) {
            addCriterion("set_lap >=", value, "setLap");
            return (Criteria) this;
        }

        public Criteria andSetLapLessThan(Short value) {
            addCriterion("set_lap <", value, "setLap");
            return (Criteria) this;
        }

        public Criteria andSetLapLessThanOrEqualTo(Short value) {
            addCriterion("set_lap <=", value, "setLap");
            return (Criteria) this;
        }

        public Criteria andSetLapIn(List<Short> values) {
            addCriterion("set_lap in", values, "setLap");
            return (Criteria) this;
        }

        public Criteria andSetLapNotIn(List<Short> values) {
            addCriterion("set_lap not in", values, "setLap");
            return (Criteria) this;
        }

        public Criteria andSetLapBetween(Short value1, Short value2) {
            addCriterion("set_lap between", value1, value2, "setLap");
            return (Criteria) this;
        }

        public Criteria andSetLapNotBetween(Short value1, Short value2) {
            addCriterion("set_lap not between", value1, value2, "setLap");
            return (Criteria) this;
        }

        public Criteria andSetStrokeIsNull() {
            addCriterion("set_stroke is null");
            return (Criteria) this;
        }

        public Criteria andSetStrokeIsNotNull() {
            addCriterion("set_stroke is not null");
            return (Criteria) this;
        }

        public Criteria andSetStrokeEqualTo(Short value) {
            addCriterion("set_stroke =", value, "setStroke");
            return (Criteria) this;
        }

        public Criteria andSetStrokeNotEqualTo(Short value) {
            addCriterion("set_stroke <>", value, "setStroke");
            return (Criteria) this;
        }

        public Criteria andSetStrokeGreaterThan(Short value) {
            addCriterion("set_stroke >", value, "setStroke");
            return (Criteria) this;
        }

        public Criteria andSetStrokeGreaterThanOrEqualTo(Short value) {
            addCriterion("set_stroke >=", value, "setStroke");
            return (Criteria) this;
        }

        public Criteria andSetStrokeLessThan(Short value) {
            addCriterion("set_stroke <", value, "setStroke");
            return (Criteria) this;
        }

        public Criteria andSetStrokeLessThanOrEqualTo(Short value) {
            addCriterion("set_stroke <=", value, "setStroke");
            return (Criteria) this;
        }

        public Criteria andSetStrokeIn(List<Short> values) {
            addCriterion("set_stroke in", values, "setStroke");
            return (Criteria) this;
        }

        public Criteria andSetStrokeNotIn(List<Short> values) {
            addCriterion("set_stroke not in", values, "setStroke");
            return (Criteria) this;
        }

        public Criteria andSetStrokeBetween(Short value1, Short value2) {
            addCriterion("set_stroke between", value1, value2, "setStroke");
            return (Criteria) this;
        }

        public Criteria andSetStrokeNotBetween(Short value1, Short value2) {
            addCriterion("set_stroke not between", value1, value2, "setStroke");
            return (Criteria) this;
        }

        public Criteria andSetDistanceIsNull() {
            addCriterion("set_distance is null");
            return (Criteria) this;
        }

        public Criteria andSetDistanceIsNotNull() {
            addCriterion("set_distance is not null");
            return (Criteria) this;
        }

        public Criteria andSetDistanceEqualTo(Short value) {
            addCriterion("set_distance =", value, "setDistance");
            return (Criteria) this;
        }

        public Criteria andSetDistanceNotEqualTo(Short value) {
            addCriterion("set_distance <>", value, "setDistance");
            return (Criteria) this;
        }

        public Criteria andSetDistanceGreaterThan(Short value) {
            addCriterion("set_distance >", value, "setDistance");
            return (Criteria) this;
        }

        public Criteria andSetDistanceGreaterThanOrEqualTo(Short value) {
            addCriterion("set_distance >=", value, "setDistance");
            return (Criteria) this;
        }

        public Criteria andSetDistanceLessThan(Short value) {
            addCriterion("set_distance <", value, "setDistance");
            return (Criteria) this;
        }

        public Criteria andSetDistanceLessThanOrEqualTo(Short value) {
            addCriterion("set_distance <=", value, "setDistance");
            return (Criteria) this;
        }

        public Criteria andSetDistanceIn(List<Short> values) {
            addCriterion("set_distance in", values, "setDistance");
            return (Criteria) this;
        }

        public Criteria andSetDistanceNotIn(List<Short> values) {
            addCriterion("set_distance not in", values, "setDistance");
            return (Criteria) this;
        }

        public Criteria andSetDistanceBetween(Short value1, Short value2) {
            addCriterion("set_distance between", value1, value2, "setDistance");
            return (Criteria) this;
        }

        public Criteria andSetDistanceNotBetween(Short value1, Short value2) {
            addCriterion("set_distance not between", value1, value2, "setDistance");
            return (Criteria) this;
        }

        public Criteria andSetCaloryIsNull() {
            addCriterion("set_calory is null");
            return (Criteria) this;
        }

        public Criteria andSetCaloryIsNotNull() {
            addCriterion("set_calory is not null");
            return (Criteria) this;
        }

        public Criteria andSetCaloryEqualTo(Short value) {
            addCriterion("set_calory =", value, "setCalory");
            return (Criteria) this;
        }

        public Criteria andSetCaloryNotEqualTo(Short value) {
            addCriterion("set_calory <>", value, "setCalory");
            return (Criteria) this;
        }

        public Criteria andSetCaloryGreaterThan(Short value) {
            addCriterion("set_calory >", value, "setCalory");
            return (Criteria) this;
        }

        public Criteria andSetCaloryGreaterThanOrEqualTo(Short value) {
            addCriterion("set_calory >=", value, "setCalory");
            return (Criteria) this;
        }

        public Criteria andSetCaloryLessThan(Short value) {
            addCriterion("set_calory <", value, "setCalory");
            return (Criteria) this;
        }

        public Criteria andSetCaloryLessThanOrEqualTo(Short value) {
            addCriterion("set_calory <=", value, "setCalory");
            return (Criteria) this;
        }

        public Criteria andSetCaloryIn(List<Short> values) {
            addCriterion("set_calory in", values, "setCalory");
            return (Criteria) this;
        }

        public Criteria andSetCaloryNotIn(List<Short> values) {
            addCriterion("set_calory not in", values, "setCalory");
            return (Criteria) this;
        }

        public Criteria andSetCaloryBetween(Short value1, Short value2) {
            addCriterion("set_calory between", value1, value2, "setCalory");
            return (Criteria) this;
        }

        public Criteria andSetCaloryNotBetween(Short value1, Short value2) {
            addCriterion("set_calory not between", value1, value2, "setCalory");
            return (Criteria) this;
        }

        public Criteria andSetEfficiencyIsNull() {
            addCriterion("set_efficiency is null");
            return (Criteria) this;
        }

        public Criteria andSetEfficiencyIsNotNull() {
            addCriterion("set_efficiency is not null");
            return (Criteria) this;
        }

        public Criteria andSetEfficiencyEqualTo(Short value) {
            addCriterion("set_efficiency =", value, "setEfficiency");
            return (Criteria) this;
        }

        public Criteria andSetEfficiencyNotEqualTo(Short value) {
            addCriterion("set_efficiency <>", value, "setEfficiency");
            return (Criteria) this;
        }

        public Criteria andSetEfficiencyGreaterThan(Short value) {
            addCriterion("set_efficiency >", value, "setEfficiency");
            return (Criteria) this;
        }

        public Criteria andSetEfficiencyGreaterThanOrEqualTo(Short value) {
            addCriterion("set_efficiency >=", value, "setEfficiency");
            return (Criteria) this;
        }

        public Criteria andSetEfficiencyLessThan(Short value) {
            addCriterion("set_efficiency <", value, "setEfficiency");
            return (Criteria) this;
        }

        public Criteria andSetEfficiencyLessThanOrEqualTo(Short value) {
            addCriterion("set_efficiency <=", value, "setEfficiency");
            return (Criteria) this;
        }

        public Criteria andSetEfficiencyIn(List<Short> values) {
            addCriterion("set_efficiency in", values, "setEfficiency");
            return (Criteria) this;
        }

        public Criteria andSetEfficiencyNotIn(List<Short> values) {
            addCriterion("set_efficiency not in", values, "setEfficiency");
            return (Criteria) this;
        }

        public Criteria andSetEfficiencyBetween(Short value1, Short value2) {
            addCriterion("set_efficiency between", value1, value2, "setEfficiency");
            return (Criteria) this;
        }

        public Criteria andSetEfficiencyNotBetween(Short value1, Short value2) {
            addCriterion("set_efficiency not between", value1, value2, "setEfficiency");
            return (Criteria) this;
        }

        public Criteria andSetIndexIsNull() {
            addCriterion("set_index is null");
            return (Criteria) this;
        }

        public Criteria andSetIndexIsNotNull() {
            addCriterion("set_index is not null");
            return (Criteria) this;
        }

        public Criteria andSetIndexEqualTo(Short value) {
            addCriterion("set_index =", value, "setIndex");
            return (Criteria) this;
        }

        public Criteria andSetIndexNotEqualTo(Short value) {
            addCriterion("set_index <>", value, "setIndex");
            return (Criteria) this;
        }

        public Criteria andSetIndexGreaterThan(Short value) {
            addCriterion("set_index >", value, "setIndex");
            return (Criteria) this;
        }

        public Criteria andSetIndexGreaterThanOrEqualTo(Short value) {
            addCriterion("set_index >=", value, "setIndex");
            return (Criteria) this;
        }

        public Criteria andSetIndexLessThan(Short value) {
            addCriterion("set_index <", value, "setIndex");
            return (Criteria) this;
        }

        public Criteria andSetIndexLessThanOrEqualTo(Short value) {
            addCriterion("set_index <=", value, "setIndex");
            return (Criteria) this;
        }

        public Criteria andSetIndexIn(List<Short> values) {
            addCriterion("set_index in", values, "setIndex");
            return (Criteria) this;
        }

        public Criteria andSetIndexNotIn(List<Short> values) {
            addCriterion("set_index not in", values, "setIndex");
            return (Criteria) this;
        }

        public Criteria andSetIndexBetween(Short value1, Short value2) {
            addCriterion("set_index between", value1, value2, "setIndex");
            return (Criteria) this;
        }

        public Criteria andSetIndexNotBetween(Short value1, Short value2) {
            addCriterion("set_index not between", value1, value2, "setIndex");
            return (Criteria) this;
        }

        public Criteria andSetTimeIsNull() {
            addCriterion("set_time is null");
            return (Criteria) this;
        }

        public Criteria andSetTimeIsNotNull() {
            addCriterion("set_time is not null");
            return (Criteria) this;
        }

        public Criteria andSetTimeEqualTo(Date value) {
            addCriterionForJDBCTime("set_time =", value, "setTime");
            return (Criteria) this;
        }

        public Criteria andSetTimeNotEqualTo(Date value) {
            addCriterionForJDBCTime("set_time <>", value, "setTime");
            return (Criteria) this;
        }

        public Criteria andSetTimeGreaterThan(Date value) {
            addCriterionForJDBCTime("set_time >", value, "setTime");
            return (Criteria) this;
        }

        public Criteria andSetTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("set_time >=", value, "setTime");
            return (Criteria) this;
        }

        public Criteria andSetTimeLessThan(Date value) {
            addCriterionForJDBCTime("set_time <", value, "setTime");
            return (Criteria) this;
        }

        public Criteria andSetTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("set_time <=", value, "setTime");
            return (Criteria) this;
        }

        public Criteria andSetTimeIn(List<Date> values) {
            addCriterionForJDBCTime("set_time in", values, "setTime");
            return (Criteria) this;
        }

        public Criteria andSetTimeNotIn(List<Date> values) {
            addCriterionForJDBCTime("set_time not in", values, "setTime");
            return (Criteria) this;
        }

        public Criteria andSetTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("set_time between", value1, value2, "setTime");
            return (Criteria) this;
        }

        public Criteria andSetTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("set_time not between", value1, value2, "setTime");
            return (Criteria) this;
        }

        public Criteria andSetRestTimeIsNull() {
            addCriterion("set_rest_time is null");
            return (Criteria) this;
        }

        public Criteria andSetRestTimeIsNotNull() {
            addCriterion("set_rest_time is not null");
            return (Criteria) this;
        }

        public Criteria andSetRestTimeEqualTo(Date value) {
            addCriterionForJDBCTime("set_rest_time =", value, "setRestTime");
            return (Criteria) this;
        }

        public Criteria andSetRestTimeNotEqualTo(Date value) {
            addCriterionForJDBCTime("set_rest_time <>", value, "setRestTime");
            return (Criteria) this;
        }

        public Criteria andSetRestTimeGreaterThan(Date value) {
            addCriterionForJDBCTime("set_rest_time >", value, "setRestTime");
            return (Criteria) this;
        }

        public Criteria andSetRestTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("set_rest_time >=", value, "setRestTime");
            return (Criteria) this;
        }

        public Criteria andSetRestTimeLessThan(Date value) {
            addCriterionForJDBCTime("set_rest_time <", value, "setRestTime");
            return (Criteria) this;
        }

        public Criteria andSetRestTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("set_rest_time <=", value, "setRestTime");
            return (Criteria) this;
        }

        public Criteria andSetRestTimeIn(List<Date> values) {
            addCriterionForJDBCTime("set_rest_time in", values, "setRestTime");
            return (Criteria) this;
        }

        public Criteria andSetRestTimeNotIn(List<Date> values) {
            addCriterionForJDBCTime("set_rest_time not in", values, "setRestTime");
            return (Criteria) this;
        }

        public Criteria andSetRestTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("set_rest_time between", value1, value2, "setRestTime");
            return (Criteria) this;
        }

        public Criteria andSetRestTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("set_rest_time not between", value1, value2, "setRestTime");
            return (Criteria) this;
        }

        public Criteria andSetSpeedIsNull() {
            addCriterion("set_speed is null");
            return (Criteria) this;
        }

        public Criteria andSetSpeedIsNotNull() {
            addCriterion("set_speed is not null");
            return (Criteria) this;
        }

        public Criteria andSetSpeedEqualTo(Short value) {
            addCriterion("set_speed =", value, "setSpeed");
            return (Criteria) this;
        }

        public Criteria andSetSpeedNotEqualTo(Short value) {
            addCriterion("set_speed <>", value, "setSpeed");
            return (Criteria) this;
        }

        public Criteria andSetSpeedGreaterThan(Short value) {
            addCriterion("set_speed >", value, "setSpeed");
            return (Criteria) this;
        }

        public Criteria andSetSpeedGreaterThanOrEqualTo(Short value) {
            addCriterion("set_speed >=", value, "setSpeed");
            return (Criteria) this;
        }

        public Criteria andSetSpeedLessThan(Short value) {
            addCriterion("set_speed <", value, "setSpeed");
            return (Criteria) this;
        }

        public Criteria andSetSpeedLessThanOrEqualTo(Short value) {
            addCriterion("set_speed <=", value, "setSpeed");
            return (Criteria) this;
        }

        public Criteria andSetSpeedIn(List<Short> values) {
            addCriterion("set_speed in", values, "setSpeed");
            return (Criteria) this;
        }

        public Criteria andSetSpeedNotIn(List<Short> values) {
            addCriterion("set_speed not in", values, "setSpeed");
            return (Criteria) this;
        }

        public Criteria andSetSpeedBetween(Short value1, Short value2) {
            addCriterion("set_speed between", value1, value2, "setSpeed");
            return (Criteria) this;
        }

        public Criteria andSetSpeedNotBetween(Short value1, Short value2) {
            addCriterion("set_speed not between", value1, value2, "setSpeed");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_set
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_set
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}