package com.may.dbTest.model;

import java.util.Date;

public class TSet {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_set.set_id
     *
     * @mbggenerated
     */
    private Long setId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_set.session_id
     *
     * @mbggenerated
     */
    private Long sessionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_set.pattern_id
     *
     * @mbggenerated
     */
    private Short patternId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_set.set_lap
     *
     * @mbggenerated
     */
    private Short setLap;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_set.set_stroke
     *
     * @mbggenerated
     */
    private Short setStroke;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_set.set_distance
     *
     * @mbggenerated
     */
    private Short setDistance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_set.set_calory
     *
     * @mbggenerated
     */
    private Short setCalory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_set.set_efficiency
     *
     * @mbggenerated
     */
    private Short setEfficiency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_set.set_index
     *
     * @mbggenerated
     */
    private Short setIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_set.set_time
     *
     * @mbggenerated
     */
    private Date setTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_set.set_rest_time
     *
     * @mbggenerated
     */
    private Date setRestTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_set.set_speed
     *
     * @mbggenerated
     */
    private Short setSpeed;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_set
     *
     * @mbggenerated
     */
    public TSet(Long setId, Long sessionId, Short patternId, Short setLap, Short setStroke, Short setDistance, Short setCalory, Short setEfficiency, Short setIndex, Date setTime, Date setRestTime, Short setSpeed) {
        this.setId = setId;
        this.sessionId = sessionId;
        this.patternId = patternId;
        this.setLap = setLap;
        this.setStroke = setStroke;
        this.setDistance = setDistance;
        this.setCalory = setCalory;
        this.setEfficiency = setEfficiency;
        this.setIndex = setIndex;
        this.setTime = setTime;
        this.setRestTime = setRestTime;
        this.setSpeed = setSpeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_set
     *
     * @mbggenerated
     */
    public TSet() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_set.set_id
     *
     * @return the value of t_set.set_id
     *
     * @mbggenerated
     */
    public Long getSetId() {
        return setId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_set.set_id
     *
     * @param setId the value for t_set.set_id
     *
     * @mbggenerated
     */
    public void setSetId(Long setId) {
        this.setId = setId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_set.session_id
     *
     * @return the value of t_set.session_id
     *
     * @mbggenerated
     */
    public Long getSessionId() {
        return sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_set.session_id
     *
     * @param sessionId the value for t_set.session_id
     *
     * @mbggenerated
     */
    public void setSessionId(Long sessionId) {
        this.sessionId = sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_set.pattern_id
     *
     * @return the value of t_set.pattern_id
     *
     * @mbggenerated
     */
    public Short getPatternId() {
        return patternId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_set.pattern_id
     *
     * @param patternId the value for t_set.pattern_id
     *
     * @mbggenerated
     */
    public void setPatternId(Short patternId) {
        this.patternId = patternId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_set.set_lap
     *
     * @return the value of t_set.set_lap
     *
     * @mbggenerated
     */
    public Short getSetLap() {
        return setLap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_set.set_lap
     *
     * @param setLap the value for t_set.set_lap
     *
     * @mbggenerated
     */
    public void setSetLap(Short setLap) {
        this.setLap = setLap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_set.set_stroke
     *
     * @return the value of t_set.set_stroke
     *
     * @mbggenerated
     */
    public Short getSetStroke() {
        return setStroke;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_set.set_stroke
     *
     * @param setStroke the value for t_set.set_stroke
     *
     * @mbggenerated
     */
    public void setSetStroke(Short setStroke) {
        this.setStroke = setStroke;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_set.set_distance
     *
     * @return the value of t_set.set_distance
     *
     * @mbggenerated
     */
    public Short getSetDistance() {
        return setDistance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_set.set_distance
     *
     * @param setDistance the value for t_set.set_distance
     *
     * @mbggenerated
     */
    public void setSetDistance(Short setDistance) {
        this.setDistance = setDistance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_set.set_calory
     *
     * @return the value of t_set.set_calory
     *
     * @mbggenerated
     */
    public Short getSetCalory() {
        return setCalory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_set.set_calory
     *
     * @param setCalory the value for t_set.set_calory
     *
     * @mbggenerated
     */
    public void setSetCalory(Short setCalory) {
        this.setCalory = setCalory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_set.set_efficiency
     *
     * @return the value of t_set.set_efficiency
     *
     * @mbggenerated
     */
    public Short getSetEfficiency() {
        return setEfficiency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_set.set_efficiency
     *
     * @param setEfficiency the value for t_set.set_efficiency
     *
     * @mbggenerated
     */
    public void setSetEfficiency(Short setEfficiency) {
        this.setEfficiency = setEfficiency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_set.set_index
     *
     * @return the value of t_set.set_index
     *
     * @mbggenerated
     */
    public Short getSetIndex() {
        return setIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_set.set_index
     *
     * @param setIndex the value for t_set.set_index
     *
     * @mbggenerated
     */
    public void setSetIndex(Short setIndex) {
        this.setIndex = setIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_set.set_time
     *
     * @return the value of t_set.set_time
     *
     * @mbggenerated
     */
    public Date getSetTime() {
        return setTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_set.set_time
     *
     * @param setTime the value for t_set.set_time
     *
     * @mbggenerated
     */
    public void setSetTime(Date setTime) {
        this.setTime = setTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_set.set_rest_time
     *
     * @return the value of t_set.set_rest_time
     *
     * @mbggenerated
     */
    public Date getSetRestTime() {
        return setRestTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_set.set_rest_time
     *
     * @param setRestTime the value for t_set.set_rest_time
     *
     * @mbggenerated
     */
    public void setSetRestTime(Date setRestTime) {
        this.setRestTime = setRestTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_set.set_speed
     *
     * @return the value of t_set.set_speed
     *
     * @mbggenerated
     */
    public Short getSetSpeed() {
        return setSpeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_set.set_speed
     *
     * @param setSpeed the value for t_set.set_speed
     *
     * @mbggenerated
     */
    public void setSetSpeed(Short setSpeed) {
        this.setSpeed = setSpeed;
    }
}